import { Knex } from "knex";

import { TableNames } from "../common/database/table_names";
import { Status } from "../common/status.enum";

export async function seed(knex: Knex): Promise<void> {
	await knex(TableNames.ROLE).insert([
		{ id: 5, name: "admin", created_by: 1 },
		{ id: 6, name: "rahbar", created_by: 1 },
		{ id: 7, name: "ishchi", created_by: 1 },
	]);
	await knex(TableNames.USERS).insert([
		{ id: 5, name: "Joe", role_id: 5, created_by: 5 },
		{ id: 6, name: "Doe", role_id: 6, created_by: 5 },
		{ id: 7, name: "Bob", role_id: 7, created_by: 5 },
	]);
	await knex(TableNames.ORGANIZATION).insert([
		{ id: 5, name: "Asku", created_by: 5 },
		{ id: 6, name: "Natija", created_by: 5 },
		{ id: 7, name: "Sodu", created_by: 5 },
	]);
	await knex(TableNames.ORGANIZATION_USER).insert([
		{ id: 5, org_id: 5, user_id: 5 },
		{ id: 6, org_id: 6, user_id: 6 },
		{ id: 7, org_id: 7, user_id: 7 },
	]);
	await knex(TableNames.PROJECT).insert([
		{ id: 5, name: "Asku Project-1", org_id: 5, created_by: 5 },
		{ id: 6, name: "Asku Project-2", org_id: 5, created_by: 5 },
		{ id: 7, name: "Asku Project-3", org_id: 5, created_by: 5 },
		{ id: 8, name: "Natija Project-1", org_id: 6, created_by: 5 },
		{ id: 9, name: "Natija Project-2", org_id: 6, created_by: 5 },
		{ id: 10, name: "Natija Project-3", org_id: 6, created_by: 5 },
		{ id: 11, name: "Sodu Project-1", org_id: 7, created_by: 5 },
		{ id: 12, name: "Sodu Project-2", org_id: 7, created_by: 5 },
		{ id: 13, name: "Sodu Project-3", org_id: 7, created_by: 5 },
	]);
	await knex(TableNames.TASK).insert([
		{
			id: 5,
			name: "Asku Task-1",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 5,
			project_id: 5,
		},
		{
			id: 6,
			name: "Asku Task-2",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 5,
			project_id: 5,
		},
		{
			id: 7,
			name: "Asku Task-3",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 1,
			project_id: 5,
		},
		{
			id: 8,
			name: "Asku Task-4",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 6,
			project_id: 6,
		},
		{
			id: 9,
			name: "Asku Task-5",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 6,
			project_id: 6,
		},
		{
			id: 10,
			name: "Asku Task-6",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 6,
			project_id: 6,
		},
		{
			id: 11,
			name: "Asku Task-7",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 7,
			project_id: 7,
		},
		{
			id: 12,
			name: "Asku Task-8",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 7,
			project_id: 7,
		},
		{
			id: 13,
			name: "Asku Task-9",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 7,
			project_id: 7,
		},
		{
			id: 14,
			name: "Natija Task-1",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 5,
			project_id: 8,
		},
		{
			id: 15,
			name: "Natija Task-2",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 5,
			project_id: 8,
		},
		{
			id: 16,
			name: "Natija Task-3",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 1,
			project_id: 8,
		},
		{
			id: 17,
			name: "Natija Task-4",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 6,
			project_id: 9,
		},
		{
			id: 18,
			name: "Natija Task-5",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 6,
			project_id: 9,
		},
		{
			id: 19,
			name: "Natija Task-6",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 6,
			project_id: 9,
		},
		{
			id: 20,
			name: "Natija Task-7",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 7,
			project_id: 10,
		},
		{
			id: 21,
			name: "Natija Task-8",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 7,
			project_id: 10,
		},
		{
			id: 22,
			name: "Natija Task-9",
			due_date: new Date(),
			done_at: new Date(),
			created_at: new Date(),
			status: Status.CREATED,
			created_by: 5,
			worker_user_id: 7,
			project_id: 10,
		},
	]);
}
